# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96fada4a613a358e5d4ef3fa982026aca8180e504e60bcd4d2861124479e52a2bbc0b43ba9142c1543aa2286ff5faf2637eae7ebb85259cce2384811615e3500

test:
  secret_key_base: 5cc3297edbab8e33245f906031a7db094cf15ac8c284c20f3c803932420813d6235c502c445a703043b93981c1e0b81092dc52ce553b88f7a59e8f9f5cf2ee19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
